#!/usr/bin/env python3
"""Existing-team bounded source recovery, not a generic executor.

Only fixed public readers/local rebuilds below can run. Durable claims and an
external checkpoint precede dispatch. Immutable kernel receipt verification is
separate and unchanged. Missing/conflicting history never bootstraps or resets.
"""
from __future__ import annotations
import argparse
import copy
from datetime import datetime, timezone
import hashlib
import json
import os
from pathlib import Path
import re
import subprocess
import sys
import tempfile

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))
from scripts import jarvis_execution as execution
from scripts import jarvis_watch as watch
from scripts.source_procedure_state import SourceProcedureStore, DEFAULT_CONFIG, TEAMS, failure_fingerprint, canonical

DIRECTORY = 'data/agents/source_procedures'
CHECKPOINT = DIRECTORY + '/checkpoint.json'
REPORT = DIRECTORY + '/report.json'
PENDING = '.source-safety-restore.pending'
HEALTHY = frozenset(('BASELINE','NO_CHANGE','CHANGED','COOLDOWN','LOCAL_VERIFIED'))
# Constants, never task/config-provided commands, URLs or modules.
COMMANDS = {
 'daiso_shortlist_observe': (('scripts/daiso/observe_shortlist.py',),),
 'dashboard_revalidate': (('scripts/health_check_v2.py',), ('scripts/generate_dashboard_runtime.py',)),
 'design_source_observe': (('scripts/collect_design_sources.py',), ('scripts/build_design_team.py',)),
 'robotics_source_observe': (('scripts/collect_robotics.py',),),
 'channel_candidate_probe': (('scripts/discover_channels.py',),),
}
NETWORK_IDS = frozenset(('daiso_shortlist_observe','design_source_observe','robotics_source_observe','channel_candidate_probe'))
SOURCES = {t: value[0] for t,value in watch.SOURCE_MAPPINGS.items() if t in TEAMS}
DEPENDENCIES = {
 'institutions': 'dated_matching_source_rows_required',
 'knowledge': 'genuine_legacy_item_capture_clocks_required',
 'graph': 'actual_native_sync_path_permission_and_heartbeat_required',
}


def now():
    return datetime.now(timezone.utc).isoformat()


def read(root, relative):
    p = execution._safe(root, relative)
    raw = p.read_bytes()
    if len(raw) > 8 * 1024 * 1024:
        raise ValueError('source_procedure_input_size')
    value = json.loads(raw)
    canonical(value)
    return value


def atomic(root, relative, value):
    if not relative.startswith(DIRECTORY + '/'):
        raise ValueError('fixed_source_procedure_write_scope')
    dest = execution._safe(root, relative)
    dest.parent.mkdir(parents=True, exist_ok=True)
    fd, temp = tempfile.mkstemp(prefix='.source-checkpoint-', dir=dest.parent)
    try:
        with os.fdopen(fd, 'wb') as stream:
            stream.write((canonical(value) + '\n').encode('utf-8'))
            stream.flush(); os.fsync(stream.fileno())
        execution._safe(root, relative)
        os.replace(temp, dest)
        if os.name != 'nt':
            directory = os.open(dest.parent, os.O_RDONLY)
            try: os.fsync(directory)
            finally: os.close(directory)
    finally:
        if os.path.exists(temp): os.unlink(temp)


def _checkpoint(root, store):
    atomic(root, CHECKPOINT, store.checkpoint())


def _stopped(value):
    if isinstance(value, dict):
        if value.get('http_status') in (401,403,429) or value.get('automatic_retry_block'):
            return True
        for key in ('error','code','error_code','failure_code','reason','parse_status'):
            text = str(value.get(key) or '').lower()
            if re.search(r'\b(?:auth_error|quota|rate_limited|robots_denied|manual_review_required)\b|robots[ _.-]+(?:deny|denied|disallow)|http(?:error)?[: ]+(?:401|403|429)\b', text):
                return True
        return any(_stopped(v) for v in value.values())
    if isinstance(value, list): return any(_stopped(v) for v in value)
    return False


def precondition(root, row, procedure, source_reads):
    team = row['source_team']
    if team in DEPENDENCIES:
        return DEPENDENCIES[team]
    if procedure not in COMMANDS:
        return 'fixed_procedure_has_no_safe_actuator'
    if procedure in NETWORK_IDS and not source_reads:
        return 'source_reads_not_enabled'
    try:
        source = read(root, row['source'])
        if _stopped(source): return 'persistent_provider_or_robots_stop'
    except (ValueError, OSError, TypeError):
        # A missing source can be collected by a fixed public reader, but no
        # existing ledger/checkpoint may be regenerated by this exception.
        if procedure not in NETWORK_IDS: return 'owned_source_input_unavailable'
    return None


def _binding(root, row, procedure):
    # Actual owned facts plus exact fixed producer inputs. Generator/assembly
    # clocks never form a new failure episode or reset its attempt allowance.
    producers = {name: hashlib.sha256(execution._safe(root, name).read_bytes()).hexdigest()
                 for command in COMMANDS.get(procedure, ()) for name in command[:1]}
    stable_hash = hashlib.sha256(canonical({'source_hash':row.get('source_hash'), 'fixed_producers':producers}).encode()).hexdigest()
    codes = row.get('blockers') or ['SOURCE_UNAVAILABLE']
    return {'source_team':row['source_team'], 'fixedprocedure_id':procedure,
            'failure_fingerprint':failure_fingerprint({'source_identity':row['source'],
              'source_hash':stable_hash, 'blocker_codes':codes})}


def dispatch(root, procedure):
    if procedure not in COMMANDS:
        raise ValueError('unknown_fixed_source_procedure')
    env = dict(os.environ, TYPESAFE_ENABLED='0', GEMINI_FALLBACK_ENABLED='0',
               GEMINI_ENABLED='0', TYPESAFE_ALLOW_PAID='0', PYTHONIOENCODING='utf-8')
    for key in ('TYPESAFE_API_KEY','GEMINI_API_KEY','GOOGLE_API_KEY','OPENAI_API_KEY',
                'ANTHROPIC_API_KEY','SERPAPI_KEY','SERP_API_KEY'):
        env.pop(key, None)
    outputs = []
    deadline = datetime.now(timezone.utc).timestamp() + (705 if procedure == 'daiso_shortlist_observe' else 600)
    for command in COMMANDS[procedure]:
        file = execution._safe(root, command[0])
        args = [sys.executable, '-B', str(file), *command[1:]]
        if procedure == 'daiso_shortlist_observe': args += ['--root', str(root)]
        remaining = max(1, deadline - datetime.now(timezone.utc).timestamp())
        try:
            result = subprocess.run(args, cwd=root, env=env, capture_output=True, timeout=remaining)
        except subprocess.TimeoutExpired as exc:
            output = b''.join(outputs) + (exc.stdout or b'') + (exc.stderr or b'')
            return 124, output[:2*1024*1024]
        outputs.append(result.stdout + result.stderr)
        if sum(map(len, outputs)) > 2*1024*1024:
            return 125, b''.join(outputs)[:2*1024*1024]
        if result.returncode: return result.returncode, b''.join(outputs)
    return 0, b''.join(outputs)


def source_proof(row, stamp):
    if (row.get('status') not in HEALTHY or row.get('blockers')
            or row.get('required_scope_complete') is False
            or (row.get('coverage') or {}).get('complete') is False):
        return None
    kind = row.get('observation_kind')
    if kind == 'source_capture': kind = 'actual_source_capture'
    if kind not in ('actual_source_capture','local_derived_read'):
        return None
    if kind == 'actual_source_capture' and not row.get('captured_at'):
        return None
    return {k: row.get(k) for k in ('source_team','source_hash','captured_at','observed_at')} | {'observation_kind':kind, 'required_scope_complete':True}


def validate_proof(root, team, proof, output, actual_output, stamp):
    if output != actual_output or not isinstance(output, bytes): return False
    observed = watch.observe(root, now=stamp)
    row = next((r for r in observed['watchers'] if r['source_team'] == team), None)
    checked = source_proof(row, stamp) if row else None
    if not checked: return False
    keys = ('source_team','source_hash','captured_at','observation_kind','required_scope_complete')
    if any(proof.get(k) != checked.get(k) for k in keys): return False
    # Source document is reread as well as parsed; no payload verified flag.
    raw = execution._safe(root, row['source']).read_bytes()
    return hashlib.sha256(raw).hexdigest() == row.get('source_document_hash')


def run(root=ROOT, *, invocation_id=None, source_reads=False, observer=None, executor=None):
    root = Path(root).absolute()
    if execution._safe(root, 'data/operations/.restore-pending.json').exists():
        raise ValueError('operations_safety_restore_pending')
    if execution._safe(root, PENDING).exists():
        raise ValueError('source_safety_restore_requires_reconciliation')
    checkpoint = read(root, CHECKPOINT)  # Required, never fresh_init here.
    store = SourceProcedureStore(execution._safe(root, DIRECTORY))
    store.load(expected=checkpoint)
    _checkpoint(root, store)  # load may mark interrupted claims.
    observer = observer or (lambda: watch.observe(root, now=now()))
    executor = executor or (lambda procedure: dispatch(root, procedure))
    invocation_id = invocation_id or ('github.' + os.environ.get('GITHUB_RUN_ID','native') + '.' + os.environ.get('GITHUB_RUN_ATTEMPT', datetime.now(timezone.utc).strftime('%Y%m%dT%H%M%S')))
    rows = {r['source_team']:r for r in observer()['watchers'] if r['source_team'] in TEAMS}
    plans, used, network_used = [], set(), False
    # Interrupted claims are never replayed or refunded. Reconcile by an actual
    # owned-source read only; original process exit/output remain UNKNOWN. This
    # preserves the reservation while permitting a later bounded retry, rather
    # than wedging the team permanently or pretending that the old call passed.
    table = store._read()
    for team, team_state in table['teams'].items():
        for episode in team_state['episodes']:
            for attempt in episode['attempts']:
                if attempt['status'] != 'reconciliation_required': continue
                stamp = now(); row = rows.get(team); proof = source_proof(row, stamp) if row else None
                try:
                    output = execution._safe(root, row['source']).read_bytes() if row else None
                    stopped = _stopped(json.loads(output)) if output else False
                except (ValueError,OSError,TypeError): output, stopped, proof = None, False, None
                end = now()
                validator = lambda a,p,o: validate_proof(root, team, p, o, output, end)
                store.reconcile(attempt['claim_id'], trusted_caller=True, exit_code=None,
                    output=output, source_proof=proof, validator=validator, stop=stopped, now=end)
                _checkpoint(root, store)
    pending = {t for t,r in store.public_projection()['teams'].items() if r['reconciliation_required']}
    for team in TEAMS:
        row = rows.get(team)
        procedure = DEFAULT_CONFIG[team][0]
        item = {'id':team,'team':team,'fixedprocedure_id':procedure,'status':'healthy_no_repair',
                'reason':'source_scope_healthy','claim_id':None,'source_healthy':False,
                'receipt_verified':False,'authority':False,'machine_eligible':False}
        if not row:
            item.update(status='waiting_owner', reason='owned_watch_source_missing')
        elif team in pending:
            item.update(status='reconciliation_required', reason='interrupted_claim_no_automatic_replay')
        elif row.get('status') not in HEALTHY or row.get('blockers'):
            reason = precondition(root, row, procedure, source_reads)
            if procedure in used: reason = 'shared_fixed_procedure_already_processed'
            if procedure in NETWORK_IDS and network_used: reason = 'one_source_actuator_per_invocation'
            if reason:
                item.update(status='waiting_owner', reason=reason)
            else:
                item['machine_eligible'] = True
                binding = _binding(root, row, procedure)
                decision = store.claim(binding, invocation_id, now=now())
                if not decision['allowed']:
                    item.update(status='bounded_hold', reason=','.join(decision['reasons']))
                else:
                    _checkpoint(root, store)  # Durability barrier BEFORE actuation.
                    used.add(procedure); network_used |= procedure in NETWORK_IDS
                    claim_id = decision['claim']['claim_id']; item['claim_id'] = claim_id
                    exit_code, output = executor(procedure)
                    if not isinstance(output, bytes): raise ValueError('actual_procedure_output_required')
                    observed_at = now()
                    fresh = next((r for r in watch.observe(root, now=observed_at)['watchers'] if r['source_team'] == team), None)
                    proof = source_proof(fresh, observed_at) if fresh else None
                    end = now()
                    validator = lambda a,p,o: validate_proof(root, team, p, o, output, end)
                    stopped = False
                    try: stopped = _stopped(read(root, (fresh or row)['source']))
                    except (ValueError,OSError,TypeError): pass
                    if stopped:
                        result = store.reconcile(claim_id, trusted_caller=True, exit_code=exit_code,
                          output=output, source_proof=proof, validator=validator, stop=True, now=end)
                    else:
                        result = store.finish(claim_id, exit_code=exit_code, output=output,
                          source_proof=proof, validator=validator, now=end)
                    _checkpoint(root, store)
                    healthy = result['outcome']['source_healthy']
                    item.update(status='source_revalidated' if healthy else 'waiting_verified_source',
                      reason='actual_owned_source_rechecked' if healthy else 'exit_zero_is_not_source_recovery',
                      source_healthy=healthy)
        plans.append(item)
    report = {'schema_version':1,'generated_at':now(), 'status':'bounded_source_recovery',
      'organization':'secretary > existing 11 team leads > specialists',
      'force_bypasses_limits':False,'source_reads_enabled':source_reads,
      'network_actuator_limit_per_invocation':1,'plans':plans,'continuity':store.public_projection(),
      'authority':False,'business_clearance':False,'receipt_verified':False}
    atomic(root, REPORT, report)
    return report


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--root', type=Path, default=ROOT)
    parser.add_argument('--invocation-id')
    parser.add_argument('--allow-source-reads', action='store_true')
    args = parser.parse_args()
    try:
        report = run(args.root, invocation_id=args.invocation_id, source_reads=args.allow_source_reads)
        print('SOURCE_PROCEDURES_OK ' + json.dumps({'teams':len(report['plans']), 'source_revalidated':sum(p['source_healthy'] for p in report['plans']), 'business_executions':0}))
        return 0
    except (ValueError,OSError,KeyError,TypeError):
        print('SOURCE_PROCEDURES_BLOCKED continuity_or_owned_source_requires_reconciliation')
        return 1

if __name__ == '__main__':
    raise SystemExit(main())
